spring:
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yu_ai_code_mother
    username: root
    password: chen
  application:
    name: yu-ai-code-mother
server:
  port: 8123
  servlet:
    context-path: /api
#springdoc-openapi
springdoc:
  group-configs:
    group: 'default'
    packages-to-scan: com.chen.yuaicodemother.controller
knife4j:
  enable: true
  setting:
    language: zh_cn
